import 'dart:convert';
import 'dart:io';

Future<void> main(List<String> args) async {
  final options = _Options.parse(args);
  if (options.showHelp) {
    stdout.writeln(_Options.usage);
    return;
  }

  final projectRoot = Directory.current;
  final constantsDir = Directory(
    '${projectRoot.path}/lib/core/constants',
  );
  final generatedFile =
      File('${constantsDir.path}/generated_dev_server_override.dart');
  final templateFile =
      File('${constantsDir.path}/generated_dev_server_override.template.dart');

  if (!templateFile.existsSync()) {
    stderr.writeln(
      'Template file not found at ${templateFile.path}. Did you clone the repo correctly?',
    );
    exit(1);
  }

  final detection = await _resolveIp();
  if (detection == null) {
    stderr.writeln(
      'Could not determine a LAN IPv4 address. Set FASTCHECK_DEV_MACHINE_IP or connect to Wi‑Fi and retry.',
    );
    exit(2);
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by tool/update_dev_machine_ip.dart.')
    ..writeln('// Platform hint: ${options.platform}.')
    ..writeln("const String generatedDevMachineIp = '${detection.ip}';")
    ..writeln("const String generatedDevMachineIpSource = '${detection.source}';")
    ..writeln(
      "const String generatedDevMachineIpGeneratedAt = '${DateTime.now().toUtc().toIso8601String()}';",
    );
  final contents = buffer.toString();

  if (options.dryRun) {
    stdout.writeln(
      '[dry-run] Would write ${detection.ip} (source: ${detection.source}) to ${generatedFile.path}',
    );
    return;
  }

  constantsDir.createSync(recursive: true);
  if (generatedFile.existsSync()) {
    final current = generatedFile.readAsStringSync();
    if (current == contents) {
      stdout.writeln(
        'generated_dev_server_override.dart already up to date (${detection.ip}).',
      );
      return;
    }
  }

  final tmpFile = File('${generatedFile.path}.tmp');
  tmpFile.writeAsStringSync(contents);
  tmpFile.renameSync(generatedFile.path);

  stdout.writeln(
    'Updated generated_dev_server_override.dart with ${detection.ip} (source: ${detection.source}).',
  );
}

class _Options {
  _Options({
    required this.dryRun,
    required this.platform,
    required this.showHelp,
  });

  final bool dryRun;
  final String platform;
  final bool showHelp;

  static const usage = '''
Usage: flutter pub run tool/update_dev_machine_ip.dart [--dry-run] [--platform=<name>]

Options:
  --dry-run          Print the detected IP without writing the generated file.
  --platform=<name>  Optional metadata for the generator (ios/android/cli).
  --help             Show this message.
''';

  static _Options parse(List<String> args) {
    var dryRun = false;
    var platform = 'unspecified';
    var showHelp = false;
    for (final arg in args) {
      if (arg == '--dry-run') {
        dryRun = true;
        continue;
      }
      if (arg == '--help' || arg == '-h') {
        showHelp = true;
        continue;
      }
      if (arg.startsWith('--platform=')) {
        platform = arg.substring('--platform='.length);
        continue;
      }
    }
    return _Options(dryRun: dryRun, platform: platform, showHelp: showHelp);
  }
}

class _DetectionResult {
  _DetectionResult({required this.ip, required this.source});

  final String ip;
  final String source;
}

Future<_DetectionResult?> _resolveIp() async {
  final envIp = _normalizeIp(
    Platform.environment['FASTCHECK_DEV_MACHINE_IP'],
  );
  if (envIp != null) {
    await _warnIfPortClosed(envIp);
    return _DetectionResult(ip: envIp, source: 'env');
  }

  for (final interface in const ['en0', 'en1', 'en2']) {
    final ip = await _ipForInterface(interface);
    if (ip != null) {
      await _warnIfPortClosed(ip);
      return _DetectionResult(ip: ip, source: interface);
    }
  }

  final ip = await _firstPrivateIpFromIfconfig();
  if (ip != null) {
    await _warnIfPortClosed(ip);
    return _DetectionResult(ip: ip, source: 'ifconfig-scan');
  }

  return null;
}

Future<String?> _ipForInterface(String interface) async {
  try {
    final process = await Process.run(
      'ipconfig',
      ['getifaddr', interface],
      stdoutEncoding: utf8,
      stderrEncoding: utf8,
    );
    if (process.exitCode != 0) {
      return null;
    }
    return _normalizeIp(process.stdout.toString());
  } on ProcessException {
    return null;
  }
}

Future<String?> _firstPrivateIpFromIfconfig() async {
  try {
    final process = await Process.run(
      'ifconfig',
      const [],
      stdoutEncoding: utf8,
      stderrEncoding: utf8,
    );
    if (process.exitCode != 0) return null;
    final regex = RegExp(
      r'inet\s+((?:\d{1,3}\.){3}\d{1,3})',
      multiLine: true,
    );
    for (final match in regex.allMatches(process.stdout as String)) {
      final ip = match.group(1);
      if (ip != null && _isPrivateIpv4(ip)) {
        return ip;
      }
    }
  } on ProcessException {
    return null;
  }
  return null;
}

String? _normalizeIp(String? value) {
  if (value == null) return null;
  final trimmed = value.trim();
  if (trimmed.isEmpty || trimmed == '0.0.0.0') return null;
  if (!_isIpv4(trimmed)) {
    stderr.writeln('Ignoring non-ip value "$trimmed".');
    return null;
  }
  return trimmed;
}

bool _isIpv4(String value) {
  final parts = value.split('.');
  if (parts.length != 4) return false;
  for (final part in parts) {
    final number = int.tryParse(part);
    if (number == null || number < 0 || number > 255) return false;
  }
  return true;
}

bool _isPrivateIpv4(String value) {
  final parts = value.split('.').map(int.parse).toList();
  if (parts.length != 4) return false;
  if (parts[0] == 10) return true;
  if (parts[0] == 192 && parts[1] == 168) return true;
  if (parts[0] == 172 && parts[1] >= 16 && parts[1] <= 31) return true;
  return false;
}

Future<void> _warnIfPortClosed(String ip) async {
  const backendPort = 8080;
  final isOpen = await _probePort(ip, backendPort);
  if (!isOpen) {
    stdout.writeln(
      '[warn] $ip:$backendPort is not reachable. Is the backend running or firewall open?',
    );
  }
}

Future<bool> _probePort(String host, int port) async {
  try {
    final process = await Process.run(
      'nc',
      ['-z', '-w', '2', host, '$port'],
      stdoutEncoding: utf8,
      stderrEncoding: utf8,
    );
    if (process.exitCode == 0) {
      return true;
    }
  } on ProcessException {
    // Fallback to a socket connect test if nc is not available.
    try {
      final socket = await Socket.connect(
        host,
        port,
        timeout: const Duration(seconds: 2),
      );
      socket.destroy();
      return true;
    } catch (_) {
      return false;
    }
  }
  return false;
}
